import { createServerFn } from "@tanstack/react-start";
import {
  ARCHITECTURE_PROMPTS,
  type ArchitectureId,
} from "../../../backend/lib/prompts";

interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
}

// Server function that securely makes calls to the Gemini API
export const executeCognitiveUplink = createServerFn({ method: "POST" })
  .validator((data: { architecture: ArchitectureId; input: string }) => data)
  .handler(async ({ data: { architecture, input } }) => {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey || apiKey === "your-api-key-here") {
      throw new Error("GEMINI_API_KEY is not configured on the server.");
    }

    const archConfig = ARCHITECTURE_PROMPTS[architecture];
    if (!archConfig) {
      throw new Error(`Unknown architecture: ${architecture}`);
    }

    try {
      const response = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [{ text: `Input concept to process: "${input}"` }],
              },
            ],
            systemInstruction: {
              parts: [{ text: archConfig.systemPrompt }],
            },
            generationConfig: {
              responseMimeType: "application/json",
              temperature: archConfig.temperature,
            },
          }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(
          `Gemini API returned status ${response.status}: ${errorText}`
        );
      }

      const json = (await response.json()) as GeminiResponse;
      const rawText = json.candidates?.[0]?.content?.parts?.[0]?.text;

      if (!rawText) {
        throw new Error("No response content generated by Gemini.");
      }

      return JSON.parse(rawText.trim());
    } catch (error) {
      console.error(`[Xeno API Server Error] [${architecture}]:`, error);
      throw error;
    }
  });
